CREATE TABLE IF NOT EXISTS supplies_userprofile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id bigint REFERENCES supplies_department(id) ON DELETE SET NULL,
    user_id integer NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
    role varchar(10) NOT NULL DEFAULT 'staff',
    CONSTRAINT supplies_userprofile_user_id_key UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS supplies_userprofile_department_id_idx ON supplies_userprofile(department_id);

ALTER TABLE supplies_annualprocurementplan ADD COLUMN IF NOT EXISTS date_requested date;
