# Generated by Django 6.0 on 2025-12-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0010_annualprocurementplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annualprocurementplan",
            name="quantity_approved",
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="apr",
            field=models.PositiveIntegerField(default=0, verbose_name="Apr"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="aug",
            field=models.PositiveIntegerField(default=0, verbose_name="Aug"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="dec",
            field=models.PositiveIntegerField(default=0, verbose_name="Dec"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="feb",
            field=models.PositiveIntegerField(default=0, verbose_name="Feb"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="jan",
            field=models.PositiveIntegerField(default=0, verbose_name="Jan"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="jul",
            field=models.PositiveIntegerField(default=0, verbose_name="Jul"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="jun",
            field=models.PositiveIntegerField(default=0, verbose_name="Jun"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="mar",
            field=models.PositiveIntegerField(default=0, verbose_name="Mar"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="may",
            field=models.PositiveIntegerField(default=0, verbose_name="May"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="nov",
            field=models.PositiveIntegerField(default=0, verbose_name="Nov"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="oct",
            field=models.PositiveIntegerField(default=0, verbose_name="Oct"),
        ),
        migrations.AddField(
            model_name="annualprocurementplan",
            name="sep",
            field=models.PositiveIntegerField(default=0, verbose_name="Sep"),
        ),
    ]
