# Generated by Django 5.2.5 on 2026-01-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0011_remove_annualprocurementplan_quantity_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="supplier",
        ),
    ]
