# Generated by Django 5.2.5 on 2026-01-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0019_stockbatch_expiry_date_delivery_stockbatch_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbatch',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='expiry_date',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
