# Generated by Django 5.2.5 on 2026-04-16 02:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0020_remove_stockbatch_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='chief_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_ps_dbm',
            field=models.BooleanField(default=False, verbose_name='Is Procurement Service (DBM)?'),
        ),
        migrations.AlterField(
            model_name='annualprocurementplan',
            name='quantity_consumed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin Validation (Aaron)'), ('for_approval', 'For Chief Approval (Isagani)'), ('approved', 'Ready for Pickup/Delivery'), ('returned', 'Returned to Sender'), ('delivered', 'Completed/Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, help_text='Stock No / Item Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g., pc, box, ream', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('dept_staff', 'Department Staff'), ('dept_head', 'Head of Unit'), ('wh_staff', 'SPMO Warehouse Staff (Edgardo)'), ('admin_ast', 'SPMO Admin Assistant (Grexxy)'), ('admin_off', 'SPMO Admin Officer (Aaron)'), ('spmo_chief', 'SPMO Chief (Isagani)')], default='dept_staff', max_length=20),
        ),
        migrations.CreateModel(
            name='APRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apr_no', models.CharField(max_length=50, unique=True, verbose_name='PS APR No.')),
                ('control_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Agency Control No.')),
                ('date_prepared', models.DateField(default=django.utils.timezone.now)),
                ('mode_of_delivery', models.CharField(choices=[('PICKUP_FAST', 'Pick-up (Fast Lane)'), ('PICKUP_SCHEDULE', 'Pick-up (Schedule)'), ('DELIVERY', 'Delivery (door-to-door)')], default='PICKUP_FAST', max_length=20)),
                ('insufficient_fund_action', models.CharField(choices=[('REDUCE', 'Reduce Quantity'), ('BILL', 'Bill Us'), ('CHARGE_DEPOSIT', 'Charge to Unutilized Deposit')], default='REDUCE', max_length=20)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_chief_approved', models.BooleanField(default=False)),
                ('is_head_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Preparing'), ('FOR_VALIDATION', 'For Admin Validation (Aaron)'), ('FOR_CHIEF', 'For Chief Approval (Isagani)'), ('FOR_HEAD', 'For Agency Head Approval'), ('SENT', 'Sent to PS-DBM'), ('PAID', 'Paid / Funds Deposited'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('CLOSED', 'Closed / Fully Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('check_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Check No. (If Paid)')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_aprs', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(limit_choices_to={'is_ps_dbm': True}, on_delete=django.db.models.deletion.CASCADE, to='supplies.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='APRItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.product')),
                ('apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.aprrequest')),
            ],
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='apr_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batches', to='supplies.aprrequest'),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_type', models.CharField(choices=[('OUTGOING', 'Customer / Dept Order'), ('INCOMING', 'Supplier / APR Procurement')], max_length=20)),
                ('order_id', models.PositiveIntegerField(help_text='The ID of the linked Order or APRRequest')),
                ('is_settled', models.BooleanField(default=False)),
                ('date_settled', models.DateField(blank=True, null=True)),
                ('reference_no', models.CharField(help_text='DV No., Check No., or OR No.', max_length=150)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='settlements/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
