# Generated by Django 5.2.5 on 2026-04-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0021_order_admin_validated_order_chief_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprrequest',
            name='mode_of_delivery',
        ),
        migrations.AddField(
            model_name='aprrequest',
            name='delivery_mode',
            field=models.CharField(choices=[('PICKUP', 'Pick-up'), ('DELIVERY', 'Delivery to Site'), ('COURIER', 'Third-Party Courier')], default='PICKUP', max_length=20),
        ),
    ]
