# Generated by Django 5.2.5 on 2026-04-17 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0022_remove_aprrequest_mode_of_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprrequest',
            name='delivery_mode',
        ),
        migrations.AddField(
            model_name='aprrequest',
            name='mode_of_delivery',
            field=models.CharField(choices=[('PICKUP_FAST', 'Pick-up (Fast Lane)'), ('PICKUP_SCHEDULE', 'Pick-up (Schedule)'), ('DELIVERY', 'Delivery (door-to-door)')], default='PICKUP_FAST', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_number', models.CharField(max_length=100, verbose_name='Delivery Receipt No.')),
                ('si_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Invoice No.')),
                ('dr_scan', models.FileField(blank=True, null=True, upload_to='deliveries/dr/')),
                ('si_scan', models.FileField(blank=True, null=True, upload_to='deliveries/si/')),
                ('signed_apr_scan', models.FileField(blank=True, null=True, upload_to='deliveries/apr/')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='supplies.aprrequest')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='delivery_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='supplies.deliveryrecord'),
        ),
    ]
