# Generated by Django 5.2.5 on 2026-04-17 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0023_remove_aprrequest_delivery_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='urgency',
            field=models.CharField(choices=[('URGENT', 'Critical Alert / Pulse'), ('INFO', 'General News / Info'), ('SUCCESS', 'Success / Update')], default='INFO', max_length=10),
        ),
    ]
