# Generated by Django 5.2.5 on 2026-05-13 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0024_news_author_news_urgency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification_letter', models.FileField(upload_to='emergency/justifications/')),
                ('supplemental_app', models.FileField(upload_to='emergency/app_amendments/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Drafting'), ('pending_ao', 'Pending Admin Officer Validation'), ('pending_supervisor', 'Pending Store Supervisor Review'), ('pending_chief', 'Pending Chief Final Approval'), ('approved', 'Approved - Form Access Granted'), ('rejected', 'Rejected / Needs Revision'), ('completed', 'Order Finalized')], default='pending_ao', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.department')),
                ('linked_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_meta', to='supplies.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
