# Generated by Django 5.2.5 on 2026-05-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0025_emergencyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('dept_ao', 'Department Admin Officer'), ('unit_head', 'Head of Unit / Office'), ('store_ao', 'Store Admin Officer (Egay)'), ('store_sup', 'Store Supervisor (Aaron)'), ('spmo_chief', 'SSPMO Chief (Isagani)')], default='dept_ao', max_length=20),
        ),
    ]
