# Generated by Django 5.2.5 on 2026-05-14 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0026_order_is_emergency_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='procurement_docs/')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Sales Invoice'), ('RECEIPT', 'Official Receipt (OR)'), ('DR', 'Delivery Receipt'), ('APR', 'Scanned APR Form'), ('INSPECTION', 'Inspection & Acceptance Report (IAR)'), ('OTHER', 'Other Supporting Doc')], default='OTHER', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='supplies.aprrequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
