# Generated by Django 5.2.5 on 2026-05-14 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0027_procurementdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aprrequest',
            name='has_unregistered_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aprrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprrequest',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_aprs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aprrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft/Preparing'), ('VERIFICATION_PENDING', 'Pending Supervisor Verification'), ('VERIFIED', 'Verified & Released to Store'), ('PARTIAL', 'Partially Received'), ('CLOSED', 'Closed/Fully Received'), ('CANCELLED', 'Cancelled')], default='VERIFICATION_PENDING', max_length=20),
        ),
    ]
