# Generated by Django 5.2.5 on 2026-05-14 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0028_aprrequest_has_unregistered_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apritem',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apritem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.product'),
        ),
    ]
