# Generated by Django 5.2.5 on 2026-05-14 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0029_apritem_remarks_alter_apritem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dv_file',
            field=models.FileField(blank=True, null=True, upload_to='order_settlements/'),
        ),
        migrations.AddField(
            model_name='order',
            name='dv_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disbursement Voucher No.'),
        ),
        migrations.AddField(
            model_name='order',
            name='dv_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dv_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dv_verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin Validation (Aaron)'), ('for_approval', 'For Chief Approval (Isagani)'), ('approved', 'Ready for Pickup/Delivery'), ('delivered_pending_settlement', 'Delivered (Awaiting DV Upload)'), ('completed', 'Completed & Settled'), ('returned', 'Returned to Sender'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
