# Generated by Django 5.2.5 on 2026-05-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0030_order_dv_file_order_dv_no_order_dv_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
