# Generated by Django 5.2.5 on 2026-03-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_assetlossreport_assetreturnrequest_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmovementlog',
            name='clearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='inventory.propertyclearancerequest'),
        ),
        migrations.AddField(
            model_name='workflowmovementlog',
            name='loss_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='inventory.assetlossreport'),
        ),
        migrations.AddField(
            model_name='workflowmovementlog',
            name='return_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='inventory.assetreturnrequest'),
        ),
    ]
