# Generated by Django 5.2.5 on 2026-03-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowmovementlog_clearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmovementlog',
            name='signature_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/snapshots/'),
        ),
    ]
