# Generated by Django 5.2.5 on 2026-03-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflowmovementlog_signature_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='position_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Official Position Title'),
        ),
        migrations.AddField(
            model_name='persona',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/personas/', verbose_name='Digital Signature'),
        ),
    ]
