# Generated by Django 5.2.5 on 2026-04-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_persona_position_title_persona_signature_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionprocess',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='actionprocess',
            name='order',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
