# Generated by Django 5.2.5 on 2026-05-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_actionprocess_options_actionprocess_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('OPERATOR', 'GAMIT Operator (SPMO Core)'), ('CLIENT', 'Client Unit Staff'), ('SYSTEM', 'System / Dev Roles')], default='CLIENT', max_length=30),
        ),
    ]
