# Generated by Django 5.2.5 on 2026-01-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='content',
            field=models.TextField(blank=True, help_text='The full article content for the popup', null=True),
        ),
    ]
