# Generated by Django 6.0.1 on 2026-02-02 02:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_newspost_created_at_newspost_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('INSP', 'Inspection'), ('TRNG', 'Training'), ('EVNT', 'Event'), ('BAG', 'Brownbag Session'), ('COLLAB', 'Inter-CU Collab'), ('DEPL', 'System Deployment'), ('OTHER', 'Other Activity')], default='EVNT', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(help_text='Building, Room, or Online Link', max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Scheduled'), ('LIVE', 'In Progress'), ('DONE', 'Completed'), ('POST', 'Postponed'), ('CANC', 'Cancelled')], default='PLANNED', max_length=10)),
                ('external_link', models.URLField(blank=True, help_text='Registration or Meeting Link', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show on the Public Hub')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['start_date'],
            },
        ),
    ]
