# Generated by Django 5.2.5 on 2026-03-26 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(choices=[('PAL', 'Philippine Airlines'), ('CEB', 'Cebu Pacific')], max_length=3, unique=True)),
                ('total_credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Allocation')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Remaining Balance')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airline Credit Balance',
                'verbose_name_plural': 'Airline Credit Balances',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Office Code')),
                ('is_mother_unit', models.BooleanField(default=False, help_text='Checked if this is a primary Mother Unit')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('full_name', models.CharField(max_length=200, verbose_name='Official Name of Traveler')),
                ('employee_id', models.CharField(max_length=50, verbose_name='Employee ID')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('up_mail', models.EmailField(max_length=254, verbose_name='UP Mail')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Contact Phone Number')),
                ('admin_officer', models.CharField(max_length=200, verbose_name='Admin Officer (Requesting Staff)')),
                ('purpose', models.TextField(verbose_name='Purpose of Travel')),
                ('trip_type', models.CharField(choices=[('ONE_WAY', 'One-Way'), ('ROUND_TRIP', 'Round-Trip'), ('MULTI_CITY', 'Multi-City')], default='ROUND_TRIP', max_length=20)),
                ('origin', models.CharField(default='Manila', max_length=255, verbose_name='Origin (Departure From)')),
                ('destination_details', models.CharField(max_length=255, verbose_name='Destination (Arrival At)')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField(verbose_name='Specific Time (Departure)')),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True, verbose_name='Specific Time (Return)')),
                ('is_official', models.BooleanField(default=False, verbose_name='Is this Travel Official and Approved?')),
                ('airline', models.CharField(choices=[('PAL', 'Philippine Airlines'), ('CEB', 'Cebu Pacific')], max_length=20)),
                ('seat_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business Class'), ('PREMIUM', 'Premium / First Class')], default='ECONOMY', max_length=20)),
                ('avail_insurance', models.BooleanField(default=False, verbose_name='Avail Travel Insurance?')),
                ('baggage_type', models.CharField(choices=[('HAND_CARRY', 'Hand-carry only'), ('CHECK_IN', 'Additional check-in baggage')], default='HAND_CARRY', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('supervisor_name', models.CharField(max_length=200, verbose_name="Immediate Supervisor's Name")),
                ('supervisor_email', models.EmailField(max_length=254, verbose_name="Supervisor's Email")),
                ('approval_date', models.DateField(verbose_name='Date of Approval')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('agreed_to_policy', models.BooleanField(default=False, verbose_name='I hereby certify that information is true')),
                ('doc_signed_slip', models.FileField(blank=True, null=True, upload_to='docs/ris/', verbose_name='Signed Requisition Slip (RIS)')),
                ('doc_travel_order', models.FileField(blank=True, null=True, upload_to='docs/to/', verbose_name='Approved Travel Order')),
                ('doc_gov_id', models.FileField(blank=True, null=True, upload_to='docs/ids/', verbose_name='Government Issued ID')),
                ('doc_itinerary', models.FileField(blank=True, null=True, upload_to='docs/itin/', verbose_name='Itinerary / Invitation Letter')),
                ('doc_previous_gfa', models.FileField(blank=True, null=True, upload_to='docs/prev/', verbose_name='Previous GFA (If Rebooking)')),
                ('booking_reference_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Airline Booking Ref / PNR')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Ticket Cost (PHP)')),
                ('doc_flight_ticket', models.FileField(blank=True, null=True, upload_to='docs/tickets/', verbose_name='Official Airline Ticket')),
                ('doc_voucher', models.FileField(blank=True, null=True, upload_to='docs/vouchers/', verbose_name='Hotel/Other Voucher')),
                ('admin_instructions', models.TextField(blank=True, help_text='Instructions for the traveler', null=True)),
                ('ticket_issued_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Printing'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved (Processing)'), ('BOOKED', 'Ticket Issued & Confirmed'), ('SETTLED', 'Transaction Settled'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('mother_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_unit_bookings', to='travel.department', verbose_name='Mother Unit')),
                ('unit_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_bookings', to='travel.department', verbose_name='Unit Office')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.department', verbose_name='Assigned Office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
