# Generated by Django 5.2.5 on 2026-03-26 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_newspost_visitorcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, unique=True, verbose_name='IATA Code')),
                ('name', models.CharField(max_length=255, verbose_name='Airport Name')),
                ('city_name', models.CharField(max_length=255, verbose_name='City/Area Name')),
                ('is_international', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airports', to='travel.city')),
            ],
            options={
                'ordering': ['city_name'],
            },
        ),
    ]
