# Generated by Django 5.2.5 on 2026-03-26 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_airport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_officer', models.CharField(max_length=200, verbose_name='Admin Officer (Requesting Staff)')),
                ('purpose', models.TextField(verbose_name='Purpose of Travel')),
                ('trip_type', models.CharField(choices=[('ONE_WAY', 'One-Way'), ('ROUND_TRIP', 'Round-Trip'), ('MULTI_CITY', 'Multi-City')], default='ROUND_TRIP', max_length=20)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField(verbose_name='Preferred Departure Time')),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True, verbose_name='Preferred Return Time')),
                ('is_official', models.BooleanField(default=False, verbose_name='Official & Approved Travel?')),
                ('airline', models.CharField(choices=[('PAL', 'Philippine Airlines'), ('CEB', 'Cebu Pacific')], max_length=20)),
                ('seat_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business Class'), ('PREMIUM', 'Premium / First Class')], default='ECONOMY', max_length=20)),
                ('baggage_type', models.CharField(choices=[('HAND_CARRY', 'Hand-carry only'), ('CHECK_IN', 'Additional check-in baggage')], default='HAND_CARRY', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('supervisor_name', models.CharField(max_length=200, verbose_name='Immediate Supervisor')),
                ('supervisor_email', models.EmailField(max_length=254, verbose_name='Supervisor Email')),
                ('approval_date', models.DateField(verbose_name='Date of Approval')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('doc_signed_slip', models.FileField(blank=True, null=True, upload_to='trips/ris/', verbose_name='Signed RIS')),
                ('doc_travel_order', models.FileField(blank=True, null=True, upload_to='trips/to/', verbose_name='Approved Travel Order')),
                ('doc_itinerary', models.FileField(blank=True, null=True, upload_to='trips/itin/', verbose_name='Itinerary / Invitation')),
                ('doc_previous_gfa', models.FileField(blank=True, null=True, upload_to='trips/prev/', verbose_name='Previous GFA (Rebooking)')),
                ('booking_reference_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='PNR / Booking Ref')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Cost (PHP)')),
                ('admin_instructions', models.TextField(blank=True, null=True)),
                ('ticket_issued_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Printing'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved (Processing)'), ('BOOKED', 'Ticket Issued & Confirmed'), ('SETTLED', 'Transaction Settled'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='travel.airport', verbose_name='Destination Airport')),
                ('legacy_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip', to='travel.bookingrequest')),
                ('mother_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_unit_trips', to='travel.department', verbose_name='Mother Unit')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='travel.airport', verbose_name='Origin Airport')),
                ('unit_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_trips', to='travel.department', verbose_name='Unit Office')),
            ],
            options={
                'verbose_name': 'Travel Trip',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassengerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('employee_id', models.CharField(max_length=50, verbose_name='Employee ID')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('up_mail', models.EmailField(max_length=254, verbose_name='UP Mail')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Contact Number')),
                ('doc_gov_id', models.FileField(blank=True, null=True, upload_to='passengers/ids/', verbose_name='Government ID')),
                ('doc_flight_ticket', models.FileField(blank=True, null=True, upload_to='passengers/tickets/', verbose_name='E-Ticket')),
                ('doc_voucher', models.FileField(blank=True, null=True, upload_to='passengers/vouchers/', verbose_name='Voucher')),
                ('avail_insurance', models.BooleanField(default=False, verbose_name='Travel Insurance?')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='travel.traveltrip')),
            ],
            options={
                'verbose_name': 'Passenger Record',
                'ordering': ['full_name'],
            },
        ),
    ]
