# Generated by Django 5.2.5 on 2025-12-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_bookingrequest_doc_previous_gfa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="admin_instructions",
            field=models.TextField(
                blank=True, help_text="Instructions for the traveler", null=True
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="booking_reference_no",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Airline Booking Ref / PNR",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="doc_flight_ticket",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="docs/tickets/",
                verbose_name="Official Airline Ticket",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="doc_voucher",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="docs/vouchers/",
                verbose_name="Hotel/Other Voucher",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="ticket_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft / Printing"),
                    ("PENDING", "Pending Review"),
                    ("APPROVED", "Approved (Processing)"),
                    ("BOOKED", "Ticket Issued & Confirmed"),
                    ("RETURNED", "Returned"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
