# Generated by Django 5.2.5 on 2026-03-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_creditlog_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='legacy_bookings',
            field=models.ManyToManyField(blank=True, related_name='settlements', to='travel.bookingrequest'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='settlements', to='travel.traveltrip'),
        ),
    ]
