# Generated by Django 5.2.5 on 2026-04-14 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_settlement_legacy_bookings_settlement_trips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='legacy_bookings',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='trips',
        ),
        migrations.AddField(
            model_name='creditlog',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_logs', to='travel.settlement'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='legacy_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_record', to='travel.bookingrequest'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_record', to='travel.traveltrip'),
        ),
        migrations.AddField(
            model_name='traveltrip',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveltrip',
            name='admin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveltrip',
            name='admin_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveltrip',
            name='chief_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveltrip',
            name='chief_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveltrip',
            name='chief_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveltrip',
            name='supervisor_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveltrip',
            name='supervisor_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveltrip',
            name='supervisor_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft / Printing'), ('PENDING', 'Pending Unit AO'), ('FOR_ADMIN', 'For SPMO Admin Review (Ruby)'), ('FOR_SUPERVISOR', 'For Supervisor Verification (Aaron)'), ('FOR_CHIEF', 'For Chief Approval (Isagani)'), ('APPROVED', 'Approved (Processing)'), ('BOOKED', 'Ticket Issued & Confirmed'), ('SETTLED', 'Transaction Settled'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='traveltrip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft / Printing'), ('PENDING', 'Pending Unit AO'), ('FOR_ADMIN', 'For SPMO Admin Review (Ruby)'), ('FOR_SUPERVISOR', 'For Supervisor Verification (Aaron)'), ('FOR_CHIEF', 'For Chief Approval (Isagani)'), ('APPROVED', 'Approved (Processing)'), ('BOOKED', 'Ticket Issued & Confirmed'), ('SETTLED', 'Transaction Settled'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
