# Generated by Django 5.2.5 on 2026-04-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_traveltrip_birthday_traveltrip_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerrecord',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='passengerrecord',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='passengerrecord',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='passengerrecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='passengerrecord',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='passengerrecord',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='passengerrecord',
            name='up_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='UP Mail'),
        ),
    ]
