# Generated by Django 5.2.9 on 2025-12-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.CharField(help_text='Unique Government Property Tag', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_acquired', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assigned_office', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SERVICEABLE', 'Serviceable'), ('UNSERVICEABLE', 'Unserviceable'), ('DISPOSED', 'Disposed'), ('UNDER_REPAIR', 'Under Repair')], default='SERVICEABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
