# Generated by Django 5.2.9 on 2025-12-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('ICT EQUIPMENT', 'ICT Equipment'), ('VEHICLE', 'Vehicle'), ('AIRCONDITIONING', 'Airconditioning'), ('OFFICE EQUIPMENT', 'Office Equipment'), ('TECH_SCIENTIFIC', 'Technical and Scientific Equipment'), ('FURNITURE', 'Furniture and Fixtures'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Class/Type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_nature',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('LABORATORY', 'Laboratory'), ('SCHOOL', 'School'), ('ACCOMODATION', 'Accomodation'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Nature'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Acquisition Cost'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_office',
            field=models.CharField(max_length=100, verbose_name='Office/Unit'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_acquired',
            field=models.DateField(verbose_name='Date Acquired'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Full)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Description (Short)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='property_number',
            field=models.CharField(help_text='Unique Property Number', max_length=50, unique=True, verbose_name='Property Number'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('SERVICEABLE', 'Serviceable'), ('UNSERVICEABLE', 'Unserviceable'), ('DISPOSED', 'Disposed'), ('UNDER_REPAIR', 'Under Repair')], default='SERVICEABLE', max_length=20, verbose_name='Active_Inactive'),
        ),
    ]
