# Generated by Django 5.2.9 on 2025-12-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_asset_class_asset_asset_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='accountable_firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Officer First Name'),
        ),
        migrations.AddField(
            model_name='asset',
            name='accountable_middle_initial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Initial'),
        ),
        migrations.AddField(
            model_name='asset',
            name='accountable_surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Officer Surname'),
        ),
        migrations.AddField(
            model_name='asset',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assets/docs/', verbose_name='Attachment (File)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='cu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CU'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/', verbose_name='Asset Image'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_nature',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('LABORATORY', 'Laboratory'), ('SCHOOL', 'School'), ('ACCOMODATION', 'Accomodation'), ('OTHER', 'Other')], default='OFFICE', max_length=50, verbose_name='Nature'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='property_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Property Number'),
        ),
    ]
