# Generated by Django 5.2.5 on 2025-12-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_asset_image_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='image',
        ),
        migrations.AddField(
            model_name='asset',
            name='image_condition',
            field=models.ImageField(blank=True, null=True, upload_to='assets/condition/', verbose_name='Asset Condition Photo'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image_serial',
            field=models.ImageField(blank=True, null=True, upload_to='assets/serials/', verbose_name='Asset Serial Photo'),
        ),
    ]
