# Generated by Django 5.2.5 on 2025-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_asset_image_asset_image_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='latitude',
            field=models.FloatField(blank=True, help_text='e.g. 14.5995', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='longitude',
            field=models.FloatField(blank=True, help_text='e.g. 120.9842', null=True),
        ),
    ]
