# Generated by Django 6.0 on 2025-12-06 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_asset_latitude_asset_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Posted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('document_main', models.FileField(upload_to='batch_docs/', verbose_name='Main Document (PO/Invoice)')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False, editable=False)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('description', models.TextField(verbose_name='Specs/Description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('asset_class', models.CharField(choices=[('ICT EQUIPMENT', 'ICT Equipment'), ('VEHICLE', 'Vehicle'), ('AIRCONDITIONING', 'Airconditioning'), ('OFFICE EQUIPMENT', 'Office Equipment'), ('TECH_SCIENTIFIC', 'Technical and Scientific Equipment'), ('FURNITURE', 'Furniture and Fixtures'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.assetbatch')),
            ],
        ),
    ]
