# Generated by Django 6.0 on 2025-12-06 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_assetbatch_batchitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(verbose_name='Inspection Remarks/Request Details')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Inspection'), ('APPROVED', 'Approved / Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('document_1', models.FileField(blank=True, null=True, upload_to='inspection_docs/', verbose_name='Request Letter / Invoice')),
                ('document_2', models.FileField(blank=True, null=True, upload_to='inspection_docs/', verbose_name='Supporting Photo/Doc')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset', verbose_name='Target Asset')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
