# Generated by Django 6.0 on 2025-12-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inspectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrequest',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Remarks from the Admin', null=True),
        ),
        migrations.AddField(
            model_name='inspectionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='inspection_docs/', verbose_name='Supporting Document 1'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='inspection_docs/', verbose_name='Supporting Document 2'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='notes',
            field=models.TextField(verbose_name='Issue Description/Remarks'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='status',
            field=models.CharField(choices=[('Pending Inspection', 'Pending Inspection'), ('Approved', 'Approved'), ('Returned', 'Returned'), ('Rejected', 'Rejected')], default='Pending Inspection', max_length=50),
        ),
    ]
