# Generated by Django 6.0 on 2025-12-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inspectionrequest_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset', verbose_name='Target Asset'),
        ),
    ]
