# Generated by Django 6.0 on 2025-12-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_assetbatch_admin_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetbatch',
            name='document_main',
        ),
        migrations.AddField(
            model_name='asset',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Item ID'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_1_file',
            field=models.FileField(blank=True, null=True, upload_to='batch_docs/'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_2_file',
            field=models.FileField(blank=True, null=True, upload_to='batch_docs/'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_3_file',
            field=models.FileField(blank=True, null=True, upload_to='batch_docs/'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_4_file',
            field=models.FileField(blank=True, null=True, upload_to='batch_docs/'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_5_file',
            field=models.FileField(blank=True, null=True, upload_to='batch_docs/'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='doc_5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='accountable_firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='accountable_middle_initial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='accountable_surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Acquisition Cost'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assets/docs/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image_condition',
            field=models.ImageField(blank=True, null=True, upload_to='assets/condition/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image_serial',
            field=models.ImageField(blank=True, null=True, upload_to='assets/serials/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('SERVICEABLE', 'Serviceable'), ('UNSERVICEABLE', 'Unserviceable'), ('DISPOSED', 'Disposed'), ('UNDER_REPAIR', 'Under Repair'), ('PENDING', 'Pending Approval')], default='SERVICEABLE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='inspection_docs/'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='inspection_docs/'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='status',
            field=models.CharField(choices=[('Pending Inspection', 'Pending'), ('Approved', 'Approved'), ('Returned', 'Returned'), ('Rejected', 'Rejected')], default='Pending Inspection', max_length=50),
        ),
        migrations.DeleteModel(
            name='BatchItem',
        ),
    ]
