# Generated by Django 6.0 on 2025-12-06 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_assetbatch_document_main_asset_item_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Transferred'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='PENDING', max_length=20)),
                ('current_officer', models.CharField(max_length=150, verbose_name='Current Accountable Officer')),
                ('new_officer_firstname', models.CharField(max_length=100, verbose_name='New Officer First Name')),
                ('new_officer_surname', models.CharField(max_length=100, verbose_name='New Officer Surname')),
                ('remarks', models.TextField(verbose_name='Reason for Transfer')),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('document_1', models.FileField(upload_to='transfer_docs/', verbose_name='Transfer Form (ITR)')),
                ('document_2', models.FileField(upload_to='transfer_docs/', verbose_name='ID / Authorization')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset', verbose_name='Target Asset')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
