# Generated by Django 6.0 on 2025-12-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_assettransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='acceptance_report_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acceptance Report No.'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Order No.'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='requesting_unit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Requesting Unit'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='sales_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Invoice No.'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier Name'),
        ),
    ]
