# Generated by Django 6.0 on 2025-12-10 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_assetbatch_acceptance_report_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Qty')),
                ('description', models.CharField(max_length=255, verbose_name='Description/Particulars')),
                ('nature_of_expense', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nature of Expense')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference No.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.assetbatch')),
            ],
        ),
    ]
