# Generated by Django 6.0 on 2025-12-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_batchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='fund_cluster',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fund Cluster'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='ups_dv_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UPS DV Number'),
        ),
    ]
