# Generated by Django 6.0 on 2025-12-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_assetbatch_fund_cluster_assetbatch_ups_dv_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='batch_items/', verbose_name='Asset Image'),
        ),
    ]
