# Generated by Django 6.0 on 2025-12-15 06:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_batchitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(default=datetime.date.today, verbose_name='Date of Service')),
                ('service_type', models.CharField(choices=[('REPAIR', 'Repair'), ('MAINTENANCE', 'Preventive Maintenance'), ('UPGRADE', 'Upgrade'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], default='MAINTENANCE', max_length=50)),
                ('description', models.TextField(verbose_name='Work Done / Details')),
                ('service_provider', models.CharField(max_length=150, verbose_name='Service Provider / Technician')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cost of Service')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Next Scheduled Date')),
                ('service_document', models.FileField(blank=True, null=True, upload_to='service_docs/', verbose_name='Service Report/Receipt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='inventory.asset')),
            ],
        ),
    ]
