# Generated by Django 5.2.5 on 2026-01-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_servicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assigned_office',
            field=models.CharField(max_length=255, verbose_name='Office/Unit'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Description (Short)'),
        ),
    ]
