# Generated by Django 5.2.5 on 2026-02-12 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_asset_assigned_office_alter_asset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Department / Office Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviation (e.g. HRDO)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_office',
            field=models.CharField(max_length=255, verbose_name='Office/Unit (Legacy)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='office',
            field=models.CharField(max_length=100, verbose_name='Assigned Office Access (Legacy)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='Department'),
        ),
    ]
