# Generated by Django 5.2.5 on 2026-02-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_department_alter_asset_assigned_office_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]
