# Generated by Django 5.2.5 on 2026-02-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN_OFFICER', 'Admin Officer'), ('HEAD_OF_UNIT', 'Head of Unit'), ('USER', 'User (Staff)')], default='USER', max_length=50, verbose_name='User Role'),
        ),
    ]
