# Generated by Django 5.2.5 on 2026-02-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned Office Access (Legacy)'),
        ),
    ]
