# Generated by Django 5.2.5 on 2026-02-13 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_userprofile_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='par_file',
            field=models.FileField(blank=True, null=True, upload_to='pars/final/', verbose_name='Finalized PAR PDF'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='par_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SHA256 Hash'),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='status',
            field=models.CharField(choices=[('ANTICIPATORY', 'Anticipatory Procurement'), ('AWAITING_DELIVERY', 'Awaiting Delivery'), ('DELIVERY_VALIDATION', 'Delivery Validation'), ('FOR_INSPECTION', 'For Inspection'), ('FOR_SUPERVISOR_APPROVAL', 'For Supervisor Approval'), ('FOR_CHIEF_PRE_APPROVAL', 'For Chief Pre-Approval'), ('FOR_AO_SIGNATURE', 'For AO Signature'), ('FOR_CHIEF_FINAL_SIGNATURE', 'For Chief Final Signature'), ('PAR_RELEASED', 'PAR Released (Final)'), ('REJECTED', 'Rejected')], default='ANTICIPATORY', max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Role at time of approval')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_snapshot', models.ImageField(blank=True, null=True, upload_to='signatures/snapshots/')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='inventory.assetbatch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='signatures/', verbose_name='Digital Signature')),
                ('position_title', models.CharField(max_length=150, verbose_name='Official Position Title')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
