# Generated by Django 5.2.5 on 2026-03-03 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_assetbatch_par_file_assetbatch_par_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='accumulated_depreciation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Accumulated Depreciation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='appraisal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Appraisal Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='appraised_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Appraised Value'),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('STRAIGHT_LINE', 'Straight-Line'), ('DECLINING_BALANCE', 'Declining Balance'), ('SUM_OF_YEARS', 'Sum-of-Years Digits')], default='STRAIGHT_LINE', max_length=30, verbose_name='Depreciation Method'),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Depreciation Start Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Disposal Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_method',
            field=models.CharField(blank=True, choices=[('AUCTION', 'Public Auction'), ('CONDEMNATION', 'Condemnation'), ('DONATION', 'Donation'), ('BARTER', 'Barter'), ('TRANSFER', 'Transfer to Other Agency')], max_length=30, null=True, verbose_name='Disposal Method'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_proceeds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Disposal Proceeds'),
        ),
        migrations.AddField(
            model_name='asset',
            name='fair_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fair Market Value'),
        ),
        migrations.AddField(
            model_name='asset',
            name='fund_source',
            field=models.CharField(blank=True, choices=[('GAA', 'General Appropriations Act'), ('INCOME', 'Income'), ('TRUST', 'Trust Fund'), ('EXTERNAL', 'Externally Funded')], max_length=20, null=True, verbose_name='Fund Source'),
        ),
        migrations.AddField(
            model_name='asset',
            name='insurance_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Insurance Value'),
        ),
        migrations.AddField(
            model_name='asset',
            name='property_classification',
            field=models.CharField(blank=True, choices=[('PPE', 'Property, Plant & Equipment'), ('SEMI_EXPENDABLE', 'Semi-Expendable'), ('EXPENDABLE', 'Expendable')], max_length=20, null=True, verbose_name='Property Classification'),
        ),
        migrations.AddField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salvage/Residual Value'),
        ),
        migrations.AddField(
            model_name='asset',
            name='uacs_object_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UACS Object Code'),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Useful Life (Years)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN_OFFICER', 'Admin Officer (Legacy)'), ('HEAD_OF_UNIT', 'Head of Unit'), ('USER', 'User (Staff)'), ('SPMO_ADMIN', 'Admin Officer — SPMO'), ('ACCT_ADMIN', 'Admin Officer — Accounting')], default='USER', max_length=50, verbose_name='User Role'),
        ),
        migrations.CreateModel(
            name='AssetChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('PROPERTY', 'Property Details'), ('FINANCE', 'Finance & Valuation'), ('LIFECYCLE', 'Lifecycle'), ('GOVERNMENT', 'Government / COA')], max_length=30)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='inventory.asset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('SPMO_ADMIN', 'SPMO Officers'), ('ACCT_ADMIN', 'Accounting Officers')], max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.asset')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
