# Generated by Django 5.2.5 on 2026-03-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_asset_asset_class_alter_asset_asset_nature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assigned_office',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_nature',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('AV_BROADCAST', 'Audio/Video & Broadcast'), ('CAMERAS', 'Cameras'), ('CARS', 'Cars'), ('COMM_AUDIO', 'Communication and Audio Devices'), ('COMP_PERI_SERV', 'Computer Peripherals and Servers'), ('COPIER_PRINT', 'Copier and Printing Devices'), ('DESK_WORKSTATION', 'Desks & Workstations'), ('DESKTOP_AIO', 'Desktops and All-in-one PCs'), ('DRONES_NAV', 'Drones & Navigation'), ('FITNESS', 'Fitness Equipment'), ('FOOD_EQUIP', 'Food Equipment'), ('HVAC', 'HVAC Systems'), ('IMAGING_PHOTO', 'Imaging & Photography'), ('LAPTOPS', 'Laptops'), ('MEASURE_TEST', 'Measurement & Testing'), ('MEDICAL', 'Medical Equipment'), ('MOBILE', 'Mobile Phones'), ('MONITOR_DISPLAY', 'Monitor and Display Devices'), ('NETWORK_SEC', 'Network and Security Devices'), ('OTHER_FURNITURE', 'Other Furnitures and Fixtures'), ('POWER_ELEC', 'Power & Electrical'), ('SCIENTIFIC_LAB', 'Scientific & Laboratory Instruments'), ('SEATING', 'Seating Units'), ('SEWING_IND', 'Sewing/Industrial Machines'), ('SPECIAL_FIX', 'Specialized Fixtures'), ('SPORTS_DISPLAY', 'Sports & Display Systems'), ('SPORTS_EQUIP', 'Sports Equipment'), ('STORAGE_PRES', 'Storage & Preservation'), ('TABLETS', 'Tablets'), ('TRICYCLE', 'Tricycle'), ('WATER_SYSTEMS', 'Water Systems'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Asset Type'),
        ),
    ]
