# Generated by Django 5.2.5 on 2026-03-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_asset_assigned_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('ICT EQUIPMENT', 'ICT Equipment'), ('MACHINERY', 'Machinery'), ('MOTOR VEHICLE', 'Motor Vehicle'), ('OFFICE EQUIPMENT', 'Office Equipment'), ('TECHNICAL AND SCIENTIFIC EQUIPMENT', 'Technical and Scientific Equipment'), ('FURNITURE AND FIXTURES', 'Furniture and Fixures'), ('AIRCONDITIONING', 'Airconditioning'), ('OTHER', 'Other')], default='OTHER', max_length=150, verbose_name='PPE Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_nature',
            field=models.CharField(choices=[('AUDIO_VIDEO_AND_BROADCAST', 'Audio/Video & Broadcast'), ('CAMERAS', 'Cameras'), ('CARS', 'Cars'), ('COMMUNICATION_AND_AUDIO_DEVICES', 'Communication and Audio Devices'), ('COMPUTER_PERIPHERALS_AND_SERVERS', 'Computer Peripherals and Servers'), ('COPIER_AND_PRINTING_DEVICES', 'Copier and Printing Devices'), ('DESKS_AND_WORKSTATIONS', 'Desks & Workstations'), ('DESKTOPS_AND_ALL-IN-ONE_PCS', 'Desktops and All-in-one PCs'), ('DRONES_AND_NAVIGATION', 'Drones & Navigation'), ('FITNESS_EQUIPMENT', 'Fitness Equipment'), ('FOOD_EQUIPMENT', 'Food Equipment'), ('HVAC_SYSTEMS', 'HVAC Systems'), ('IMAGING_AND_PHOTOGRAPHY', 'Imaging & Photography'), ('LAPTOPS', 'Laptops'), ('MEASUREMENT_AND_TESTING', 'Measurement & Testing'), ('MEDICAL_EQUIPMENT', 'Medical Equipment'), ('MOBILE_PHONES', 'Mobile Phones'), ('MONITOR_AND_DISPLAY_DEVICES', 'Monitor and Display Devices'), ('NETWORK_AND_SECURITY_DEVICES', 'Network and Security Devices'), ('OTHER_FURNITURES_AND_FIXTURES', 'Other Furnitures & Fixtures'), ('POWER_AND_ELECTRICAL', 'Power & Electrical'), ('SCIENTIFIC_AND_LABORATORY_INSTRUMENTS', 'Scientific & Laboratory Instruments'), ('SEATING_UNITS', 'Seating Units'), ('SEWING_INDUSTRIAL_MACHINES', 'Sewing/Industrial Machines'), ('SPECIALIZED_FIXTURES', 'Specialized Fixtures'), ('SPORTS_AND_DISPLAY_SYSTEMS', 'Sports & Display Systems'), ('SPORTS_EQUIPMENT', 'Sports Equipment'), ('STORAGE_AND_PRESERVATION', 'Storage & Preservation'), ('TABLETS', 'Tablets'), ('TRICYCLE', 'Tricycle'), ('WATER_SYSTEMS', 'Water Systems'), ('OTHER', 'Other')], default='OTHER', max_length=100, verbose_name='Asset Type'),
        ),
    ]
