# Generated by Django 5.2.5 on 2026-03-12 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_asset_asset_class_alter_asset_asset_nature'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep', verbose_name='Current Workflow Step'),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep', verbose_name='Current Workflow Step'),
        ),
        migrations.AddField(
            model_name='inspectionrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep', verbose_name='Current Workflow Step'),
        ),
    ]
