# Generated by Django 5.2.5 on 2026-03-12 05:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_assetbatch_current_step_and_more'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLossReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('incident_date', models.DateField(default=datetime.date.today, verbose_name='Date of Incident')),
                ('description', models.TextField(verbose_name='Description of Incident')),
                ('notice_of_loss', models.FileField(upload_to='loss_docs/', verbose_name='Notice of Loss')),
                ('affidavit_of_loss', models.FileField(upload_to='loss_docs/', verbose_name='Notarized Affidavit of Loss')),
                ('police_report', models.FileField(blank=True, null=True, upload_to='loss_docs/', verbose_name='Police/Fire Report (Optional)')),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset', verbose_name='Lost/Damaged Asset')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep', verbose_name='Current Workflow Step')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('reason', models.TextField(verbose_name='Reason for Return')),
                ('original_par_document', models.FileField(upload_to='return_docs/', verbose_name='Signed Copy of Original PAR/ICS')),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset', verbose_name='Returned Asset')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep', verbose_name='Current Workflow Step')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyClearanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('routing_form', models.FileField(upload_to='clearance_docs/', verbose_name='Employee Routing / Clearance Form')),
                ('purpose', models.CharField(max_length=150, verbose_name='Purpose of Clearance (e.g., Retirement, Transfer)')),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep', verbose_name='Current Workflow Step')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
