# Generated by Django 5.2.5 on 2026-03-16 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_assetlossreport_assetreturnrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='acquisition_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_assets', to='inventory.assetbatch'),
        ),
    ]
