# Generated by Django 5.2.5 on 2026-03-17 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_asset_acquisition_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_custodian',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assigned Custodian'),
        ),
        migrations.AddField(
            model_name='asset',
            name='custodian_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/custodians/', verbose_name='Custodian Signature'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='requesting_unit_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='Requesting Unit (Object)'),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='assigned_custodian',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assigned Custodian'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='property_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Property Number'),
        ),
    ]
