# Generated by Django 5.2.5 on 2026-03-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_asset_assigned_custodian_asset_custodian_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item ID'),
        ),
    ]
