# Generated by Django 5.2.5 on 2026-03-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_asset_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Physical Location (Room/Bldg)'),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='custodian_position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Custodian Position Title'),
        ),
    ]
