# Generated by Django 5.2.5 on 2026-03-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_assetbatch_location_batchitem_custodian_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Brand/Model'),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity_physical_count',
            field=models.IntegerField(default=1, verbose_name='Physical Count Qty'),
        ),
        migrations.AddField(
            model_name='asset',
            name='unit_of_measure',
            field=models.CharField(default='pc', max_length=50, verbose_name='Unit of Measure'),
        ),
    ]
