# Generated by Django 5.2.5 on 2026-03-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_asset_brand_asset_quantity_physical_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('ICT EQUIPMENT', 'ICT Equipment'), ('MACHINERY', 'Machinery'), ('MOTOR VEHICLE', 'Motor Vehicle'), ('OFFICE EQUIPMENT', 'Office Equipment'), ('TECHNICAL AND SCIENTIFIC EQUIPMENT', 'Technical & Scientific Equipment'), ('FURNITURE AND FIXTURES', 'Furniture & Fixtures'), ('AIRCONDITIONING', 'Airconditioning'), ('OTHER', 'Other')], default='OTHER', max_length=255, verbose_name='PPE Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand/Model'),
        ),
    ]
