# Generated by Django 5.2.5 on 2026-03-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_asset_asset_class_alter_asset_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='unit_of_measure',
            field=models.CharField(default='pc', max_length=255, verbose_name='Unit of Measure'),
        ),
    ]
