# Generated by Django 5.2.5 on 2026-03-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_asset_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='accountable_firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='accountable_middle_initial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='accountable_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
