# Generated by Django 5.2.5 on 2026-03-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_asset_accountable_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='item_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='property_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Property Number'),
        ),
    ]
